os: linux
dist: bionic
services:
  - xvfb
notifications:
  email: change

language: python

python:
  - 3.6
  - 3.7

env:
  matrix:
    - CHECK_TYPE=linting
    - CHECK_TYPE=docdoctest
    - CHECK_TYPE=test
  global:
    - INSTALL_TYPE=setup
    - secure: FTG5VDvtYYy1cZh7HJXsLAF6Q2gJT0Oz/KZFWCjRnK3jIWGq7uOcr5L9Wf5PTRzLglE5x/oaj4q+wSK8j2EdcDYK0YS8fFGoRpfxcPLFV8Nl1I7ubFkfnAwAs1UhwKTyaHmcEdWsf7QrN71HzT//3/Wl2WA2GuB3PK8n8sxm2YnkKM35MeHoR/+z5XgFNuZEETJ0kVqbH7TAoyOCLoVbm8IsEjU3aY6Sd5PiiLe3ZEZNMA4y6LgCvzW/9rTNfqcUP/r7SDou1BACNA1GCGZb6yYh7OA53onRv4Bwcqk+J/2aFz9DNeG+qGbDTivypf7TPt/5KgZJcRi7bjiJqR3MfifVNzDWkfXStA/SAOUvChTB/O+bzLVc3pd06kgi3u+9fzvckCUBIBvQHVSPT7L+i1VwwuuqtCI+VhaH0mqOru6a8qTwY2GKaWXTbnN0YeKJCjaIGhcspZdMsLbrkALf9W1YMWE0a5/oYEXINC4xec8WnRaVcPXZsMxoPJ/RY9eGcrNkROBVf8xvFqA6N4Eww+9Fc/52Lg8/p2x8nq66RXWOqlZgt8pm4bF+XlXjGn+81JKruXIvnDlLwXu6keQLyWygFYGIZdtcMljVfKQ7cFuPsjpvYGwdPTr0xFcuRpx8YZBcOy3KikYJ4ly+3DvHYPx+C2QryEuiANhtpB1h3PU=

matrix:
  include:
    - python: 3.6
      env:
        - INSTALL_TYPE=sdist
        - CHECK_TYPE=test
    - python: 3.6
      env:
        - INSTALL_TYPE=wheel
        - CHECK_TYPE=test
    - language: node_js
      node_js: 10
      env:
        - INSTALL_TYPE=auto-svl
        - CHECK_TYPE=auto-svl
        - GIT_NAME="Stefano Moia"
        - GIT_EMAIL="s.moia@bcbl.eu"
        - GH_USER="smoia"

before_install:
  - if [ "${CHECK_TYPE}" == "auto-svl" ]; then
      CHECK_BRANCH=$( git branch | grep \*);
      if [ "${CHECK_BRANCH:20}" == "FETCH_HEAD)" ]; then
        echo "!!! On branch ${CHECK_BRANCH}, skipping auto-svl";
      else
        echo "!!! On branch ${CHECK_BRANCH}, preparing environment for auto-svl";
        git config --local user.name "${GIT_NAME}";
        git config --local user.email "${GIT_EMAIL}";
        echo "GH_TOKEN=${GH_TOKEN}" >> .env;
      fi;
    else
      python -m pip install --upgrade pip;
    fi
  - if [ "${CHECK_TYPE}" == "linting" ]; then
      pip install flake8;
    fi
  - if [ "${CHECK_TYPE}" == "test" ]; then
      pip install "pytest>=4.6" pytest-cov coverage coveralls codecov;
    fi
  - if [ "${CHECK_TYPE}" == "docdoctest" ]; then
      pip install "sphinx>2.0" sphinx_rtd_theme pandas sphinx-argparse;
    fi

install:
    if [ "${INSTALL_TYPE}" == "setup" ]; then
      pip install "bioread>=1.0.5";
      python setup.py install;
    elif [ "${INSTALL_TYPE}" == "sdist" ]; then
      pip install "bioread>=1.0.5";
      python setup.py sdist;
      pip install dist/*.tar.gz;
    elif [ "${INSTALL_TYPE}" == "wheel" ]; then
      pip install "bioread>=1.0.5";
      python setup.py bdist_wheel;
      pip install dist/*.whl;
    elif [ "${INSTALL_TYPE}" == "auto-svl" ]; then
      CHECK_BRANCH=$( git branch | grep \*);
      if [ "${CHECK_BRANCH:20}" == "FETCH_HEAD)" ]; then
        echo "!!! On branch ${CHECK_BRANCH}, skipping auto-svl";
      else
        echo "!!! On branch ${CHECK_BRANCH}, setting up auto-svl";
        mkdir build;
        curl -vkL -o - https://github.com/intuit/auto/releases/download/v9.39.0/auto-linux.gz | gunzip > build/auto;
        chmod a+x build/auto;
      fi;
    else
      false;
    fi

script:
  - |
    CHECK_BRANCH=$( git branch | grep \*);
    echo "**********";
    echo "******";
    echo "**";
    if [ "${CHECK_BRANCH:20}" == "FETCH_HEAD)" ]; then
      echo "!!! On branch ${CHECK_BRANCH}, this should be a **test for submitted PR**";
    else
      echo "!!! On branch ${CHECK_BRANCH}, this should be a **test after MERGE**";
    fi;
    echo "**";
    echo "******";
    echo "**********";
    if [ "${CHECK_TYPE}" == "linting" ]; then
      flake8 phys2bids;
    elif [ "${CHECK_TYPE}" == "docdoctest" ]; then
      cd docs;
      pip install -r ./requirements.txt;
      make html;
      make doctest;
    elif [ "${CHECK_TYPE}" == "test" ]; then
      mkdir for_testing && cd for_testing;
      cp ../setup.cfg ./;
      args="--doctest-modules --cov-report term-missing --cov=phys2bids --pyargs"
      python -m pytest ${args} phys2bids;
    elif [ "${CHECK_TYPE}" == "auto-svl" ]; then
      CHECK_BRANCH=$( git branch | grep \*);
      if [ "${CHECK_BRANCH:20}" == "FETCH_HEAD)" ]; then
        echo "!!! On branch ${CHECK_BRANCH}, skipping auto-svl";
      else
        echo "!!! On branch ${CHECK_BRANCH}, run auto-svl!";
        build/auto shipit;
      fi;
    else
      false;
    fi

after_success:
  - if [ "${CHECK_TYPE}" == "test" ]; then
      coveralls; codecov;
    fi
