# Adapted from https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml
pr:
  branches:
    include:
    - '*'

jobs:
- template: .azure-pipelines/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
    matrix:
      py36-x64:
        PYTHON_VERSION: '3.6'
        PYTHON_ARCH: 'x64'
      py37-x64:
        PYTHON_VERSION: '3.7'
        PYTHON_ARCH: 'x64'
      py37-x64:
        PYTHON_VERSION: '3.8'
        PYTHON_ARCH: 'x64'
      py37-x64:
        PYTHON_VERSION: '3.9'
        PYTHON_ARCH: 'x64'
